name = "tafraout-store"
compatibility_date = "2026-07-14"
main = "src/worker.js"

# هنا كنقولو ليه يقرا الملفات الثابتة من المجلد الجديد
[assets]
directory = "./public"

# الربط مع قاعدة البيانات D1
[[d1_databases]]
binding = "DB"
database_name = "tafraout-store-db"
database_id = "حط_هنا_الـ_ID_ديال_الـ_Database_ديالك" 

# هنا المتغيرات السرية اللي تشفرو
[vars]
ADMIN_PASSWORD_HASH = "PBKDF2$PBKDF2WithHmacSHA256$100000$NARSQijWGmiw7P6HVo2B2Q==$PaKyO1trA6A78j10A5rztiAkCZA6YYpFqaPq5lw9CYQ="
JWT_SECRET = "4fca92b8d1a12c3b5e8f9a2d6c8b0e1f3a5c7d9e0b2a4c6e8f0a2b4c6d8e0f12"
